= Kest image:doc/modules/ROOT/images/tinylogo.svg[alt=Kest, 55]
:toc:
:preface-title: Overview

:includedir: ROOT/pages
:documentation: doc/modules/ROOT/pages/

Full documentation can be found here: https://lemfi.github.io/kest/[]

:leveloffset: +1


:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/lemfi/kest/main/
:title-logo-image: image:doc/logo.svg[]

= Overview

== Presentation

Kest is a test framework written in Kotlin for testing your backends. +
It relies on JUnit5 to run scenarios.

Easy to use, easy to extend.

It was created to meet the need to test backends and to interact with the middlewares on which they are based in a very simple way, in order to be able to concentrate on the functional to be tested by avoiding difficulty or heaviness brought about by interactions with multiple components.

====
Use case :

My backend consumes messages in a RabbitMQ queue, it exposes its data over HTTP, HTTP access is protected.
To test the behavior of my backend I will have to:

. post messages in RabbitMQ
. provision users in my mongo database
. make HTTP requests to my backend

&#8658;
I'm going to need to interact with three different technologies, with different clients to handle. +
&#8658; Kest allows you to get away from it all +
&#8658; Kest is an engine that will play scenarios, scenarios will be a sequence of steps +
&#8658; Kest provides ready-made steps to interact with HTTP, RabbitMQ, MongoDB, Redis, and Cadence +
&#8658; Kest allows you to define your own steps: you use a techno not supported by Kest? design your steps! +
====

:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/lemfi/kest/main/
:title-logo-image: image:doc/logo.svg[]

== Use it

=== Gradle


[source,kotlin]
----
    implementation("com.github.lemfi.kest:core:0.8.0")
    implementation("com.github.lemfi.kest:junit5:0.8.0")

    // include the steps you need among available ones
    implementation("com.github.lemfi.kest:step-http:0.8.0")
    implementation("com.github.lemfi.kest:step-cadence:0.8.0")
    implementation("com.github.lemfi.kest:step-mongodb:0.8.0")
    implementation("com.github.lemfi.kest:step-rabbitmq:0.8.0")
    implementation("com.github.lemfi.kest:step-redis:0.8.0")

    // toolbox for Json Data
    implementation("com.github.lemfi.kest:json:0.8.0")

----

=== Maven

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>core</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>junit5</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>

    <!-- include the steps you need among available ones -->
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-http</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-rabbitmq</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-cadence</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-mongodb</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-redis</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>

    <!-- toolbox for Json Data -->
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-json</artifactId>
        <version>0.8.0</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----

:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/lemfi/kest/main/
:title-logo-image: image:doc/logo.svg[]

== Big picture
=== Scenarios

Kest allows you to write scenarios. +
One scenario is a sequence of steps. +
One step defines an execution and a list of assertions to validate completed execution.

Let's take following example:

[source,kotlin]
----
scenario(name = "api says hello and remembers it!") {

    givenHttpCall<String> {

        url = "http://myapi/hello"
        method = "POST"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="
        body = """
            {
                "who": "Darth Vader"
            }
        """
    } assertThat { stepResult ->

        stepResult.status isEqualTo 201
        stepResult.body  isEqualTo "Hello Darth Vader!"
    }

    givenHttpCall<String> {

        url = "http://myapi/hello"
        method = "POST"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="
        body = """
            {
                "who": "Han Solo"
            }
        """
    } assertThat { stepResult ->

        stepResult.status isEqualTo 201
        stepResult.body isEqualTo "Hello Han Solo!"
    }

    givenHttpCall<List<String>> {

        url = "http://myapi/hello"
        method = "GET"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="

    } assertThat { stepResult ->

        stepResult.status isEqualTo 200
        stepResult.body  isEqualTo listOf("Darth Vader", "Han Solo")
    }
}
----

This example defines a scenario with three steps:

. Say hello to Darth Vader
. Say hello to Han Solo
. Get list of people that were greeted

For each step 2 assertions are done:

. check status code
. check body

=== Run a scenario

To run a scenario Kest uses Junit5 engine:

. Create a class to hold your test
. Create a function annotated with Junit5 `@TestFactory`
. Make it call Kest function
.. `playScenarios` to play multiple scenarios in a single junit5 test factory +
=> in this case you can pass `beforeEach` and `afterEach` attributes representing a lambda returning a scenario to be played before and after each scenario if needed.
=> in this case you can pass `beforeEach` and `afterEach` attributes representing a lambda returning a scenario to be played before and after each scenario if needed.
.. `playScenario` to play one scenario per junit5 test factory +
=> in this case you can use junit5 annotations `@BeforeEach` and `@AfterEach`

[source,kotlin]
----

class TestHttpServer {

    @TestFactory
    fun `http server says hello`() = playScenarios(
            scenario { /*...*/ },
            scenario { /*...*/ },
            scenario { /*...*/ },

            beforeEach = { scenario { /*...*/ }},
            afterEach = { scenario { /*...*/ }}
    )


    @TestFactory
    fun `http server says goodbye`() = playScenarios(
            scenario { /*...*/ },
            scenario { /*...*/ },
            scenario { /*...*/ },

            beforeEach = { scenario { /*...*/ }},
            afterEach = { scenario { /*...*/ }}
    )

}

class TestHttpServer {

    @BeforeEach
    fun beforeEach() {
        /*...*/
    }

    @AfterEach
    fun afterEach() {
        /*...*/
    }

    @TestFactory
    fun `http server says hello - scenario 1`() = playScenario(
            scenario { /*...*/ }
    )

    @TestFactory
    fun `http server says hello - scenario 2`() = playScenario(
            scenario { /*...*/ }
    )

}
----

== Focus on how it works

image::{gitplant}/doc/diag/model.puml[]

When a scenario is launched, all its steps are launched sequentially, if one step fails the scenario fails without running remaining steps. +
When a step is launched its execution is played, then assertions are played against execution result. +
A step returns an object . which is invokable: you may reuse its result in another step . which you may complete by your own assertions, they will be added to assertions already defined on step

:leveloffset!:
:leveloffset: +1

:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/lemfi/kest/main/
:title-logo-image: image:doc/logo.svg[]

= Steps

A step is where interaction with your system happen, it:

* has a name
* can be retried
* has an execution
* has a list of assertions

[source,kotlin]
----
step(
    name = "a name a step has",
    retry = 10.times byIntervalsOf 200.ms, // if assertions of step fail, step will be retried 10 times by intervals of 200 ms before really failing. Useful if you have asynchonous stuff going on on your backends.
) {
    // here goes the definition of the execution
} assertThat {
    // here goes list of assertions
}
----

== Available Steps

=== xref:{documentation}steps/http.adoc[HTTP]
=== xref:{documentation}steps/rabbitmq.adoc[RabbitMQ]
=== xref:{documentation}steps/mongodb.adoc[Mongo]
=== Redis
=== Cadence

== Create your own step

You need custom steps not provided by Kest? Two options:

* Use generic step `step`
+
[source,kotlin]
----
step(name = "name of my step") {

    // execute your need here
    1+1

} assertThat { stepResult ->

    stepResult isEqualTo 2

}
----
* xref:{documentation}steps/create-step.adoc[Create your own one]

== Nested scenario

If you want to group some steps together to make your scenario clearer you may use a particular step that allows that

[source,kotlin,]
----
nestedScenario("group steps") {
    step(name = "step1") { /*...*/ }
    step(name = "step2") { /*...*/ }
    step(name = "step3") { /*...*/ }
}
----

== Reuse result of one step in another one

When you create a step, you call a function that will return a `StepResult` +
It's on that `StepResult` that make assertions. +
It's also on that `StepResult` that you can retrieve the result of the step.

[source,kotlin,]
----
val step1: StepResult<Int> = step { 1+1 } assertThat { it isEqualTo 2 }

val step2: StepResult<Double> = step { step1() + 1.5 } assertThat { it isEqualTo 3.5 }

step { step2.invoke().toString() } assertThat { it isEqualTo "3.5" }
----

As you can see on the example, to get the result of a step you may invoke it.

CAUTION: you may use the result of a step only in the execution of another step, if you try to invoke it outside an execution then the step will probably not have been played yet so no result will be available.

=== Special case of a nestedScenario

`nestedScenario` step is a particular step that does not return any result by default. +
It is still possible to return a result from a `nestedScenario`

[source,kotlin,]
----
val step1 = nestedScenario<Double> {

    val step11: StepResult<Int> = step { 1+1 } assertThat { it isEqualTo 2 }

    val step12: StepResult<Double> = step { step11() + 1.5 } assertThat { it isEqualTo 3.5 }

    returns { step12() }
}

step { step1() + 4 } assertThat { it isEqualTo 7.5 }
----

=== Transform the result of a step

You may transform a result of a step so that later steps reusing the result will reuse transformed result instead of initial one

[source,kotlin,]
----
val step1 = step { 1 + 1 } mapResultTo { it * 1.0 } assertThat { it isEqualTo 2 }

step { step1() * 3 } assertThat { it isEqualTo 18.0 }
----

Here step1 result was transformed from an Int to a Double  +
Even though in assertions of step 1 the result is still an Int: Assertions are always done on initial result, not transformed one. +
Then when second step invoked step1 result it got a Double +

NOTE: Take care, when you use `mapResultTo` it will not transform the result for the assertions of the step, assertions are always done on step initial result. +
Moreover,  `mapResultTo` lambda will only be executed when the result of its step will be invoked: if result of that step is never invoked, then `mapResultTo` lambda will never be executed.

:leveloffset!:
:leveloffset: +1

:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/lemfi/kest/main/

= JSON support

JSON is a common format to interact between machines, as matter of fact, Kest comes with advanced support to that format with a bunch of assertions. +
It also comes with two Objects: `JsonMap` and `JsonArray`

* `JsonMap` is a `Map<String, Any?>`
* `JsonArray` is an array of `JsonMap`

== Matchers

Kest provides several function to check whether a json content matches a Json pattern.
To do so, Kest provides by default 3 matchers:

* {\{string}}
* {\{number}}
* {\{boolean}}

For example

[source,json]
----
{
  "string": "a string",
  "number": 1,
  "boolean": true
}
----

is matched by

[source,json]
----
{
  "string": "{{string}}",
  "number": "{{number}}",
  "boolean": "{{boolean}}"
}
----

or by

[source,json]
----
{
  "string": "{{string}}",
  "number": 1,
  "boolean": "{{boolean}}"
}
----

And the function to check that with Kest would be:

[source,kotlin]
----
json(
    """
    {
      "string": "a string",
      "number": 1,
      "boolean": true
    }"""
) matches validator {
    """
    {
      "string": "{{string}}",
      "number": "{{number}}",
      "boolean": "{{boolean}}"
    }
    """
}

// OR shortcuts are provided two write it without having to remember the notation
json(
    """
    {
      "string": "a string",
      "number": 1,
      "boolean": true
    }"""
) matches validator {
    """
    {
      "string": "$stringPattern",
      "number": "$numberPattern",
      "boolean": "$booleanPattern"
    }
    """
}

----

=== Defining your own matchers

If you want to define your own matchers, several possibilities:

==== Define it textually

[source,kotlin]
----
val samplePattern = pattern("sample") definedBy """{
  "string": "$stringPattern",
  "number": "$numberPattern",
  "boolean": "$booleanPattern"
}"""
----

To check match you can now call this:

[source,kotlin]
----
json(
    """
    {
      "string": "a string",
      "number": 1,
      "boolean": true
    }"""
) matches validator {
    """
    {{sample}}
    """
}

// OR

json(
    """
    {
      "string": "a string",
      "number": 1,
      "boolean": true
    }"""
) matches samplePattern
----

==== Define a class

[source,kotlin]
----
data class Sample(
        val string: String,
        val number: Int,
        val boolean: Boolean
)
----

Then declare it as a pattern:

[source,kotlin]
----
val samplePattern = pattern("sample") definedBy Sample::class
----

To check match you can now call this:

[source,kotlin]
----
json(
    """
    {
      "string": "a string",
      "number": 1,
      "boolean": true
    }"""
) matches validator {
    """
    {{sample}}
    """
}

// OR

json(
    """
    {
      "string": "a string",
      "number": 1,
      "boolean": true
    }"""
) matches samplePattern
----

==== Define a function that will check the validity of pattern

[source,kotlin]
----
fun checkDateFormat(data: String): Boolean {
    val dateFormatter = DateTimeFormatter.ofPattern("YYYY-MM-dd").withResolverStyle(STRICT)

    return try {
        dateFormatter.parse(data)
        true
    } catch (e: DateTimeParseException) {
        false
    }
}
----

Then declare it as a pattern:

[source,kotlin]
----
val samplePattern = pattern("sample") definedBy ::checkDateFormat
----

To check match you can now call this:

[source,kotlin]
----
json(
    """
    {
      "date": "2021-01-12",
      "number": 1,
      "boolean": true
    }"""
) matches validator {
    """
    {
      "date": "{{sample}}",
      "number": "$numberPattern",
      "boolean": "$booleanPattern"
    }
    """
}
// OR

json(
    """
    {
      "date": "2021-01-12",
      "number": 1,
      "boolean": true
    }"""
) matches validator {
    """
    {
      "date": "$samplePattern",
      "number": "$numberPattern",
      "boolean": "$booleanPattern"
    }
    """
}
----

=== Lists and nullable matchers

==== Lists
What if you want to check that an array contains a list of objects validating a pattern?

[source,json]
----
{
  "data": [
    {
      "string": "a string",
      "number": 1,
      "boolean": true
    },
    {
      "string": "another string",
      "number": 2,
      "boolean": false
    }
  ]
}
----

[source,kotlin]
----
val samplePattern = pattern("sample") definedBy """{
  "string": "$stringPattern",
  "number": "$numberPattern",
  "boolean": "$booleanPattern"
}"""
----


To check match you can now call this:

[source,kotlin]
----
json(
    """
    {
      "data": [
        {
          "string": "a string",
          "number": 1,
          "boolean": true
        },
        {
          "string": "another string",
          "number": 2,
          "boolean": false
        }
      ]
    }"""
) matches validator {
    """
    {
      "data": "[[{{sample}}]]"
    }
    """
}

// OR

json(
    """
    {
      "data": [
        {
          "string": "a string",
          "number": 1,
          "boolean": true
        },
        {
          "string": "another string",
          "number": 2,
          "boolean": false
        }
      ]
    }"""
) matches validator {
    """
    {
      "data": "${jsonArrayOf(samplePattern)}",
      "number": "$numberPattern",
      "boolean": "$booleanPattern"
    }
    """
}
----

==== Nullable values

[source,kotlin]
----
val samplePattern = pattern("sample") definedBy """{
  "string": "${stringPattern.nullable}",
  "number": "$numberPattern",
  "boolean": "$booleanPattern"
}"""
----


To check match you can now call this:

[source,kotlin]
----
json(
    """
    {
          "string": null,
          "number": 1,
          "boolean": true
    }"""
) matches validator {
    """
    {
      "string": "{{string?}}",
      "number": "$numberPattern",
      "boolean": "$booleanPattern"
    }
    """
}

// OR

json(
    """
    {
          "string": null,
          "number": 1,
          "boolean": true
    }"""
) matches validator {
    """
    {
      "string": "${stringPattern.nullable}",
      "number": "$numberPattern",
      "boolean": "$booleanPattern"
    }
    """
}
----

== Polymorphism

To go through polyphormism, Kest allows you to define a list of matchers for a given JSON.

Let's take this example:

[source,json]
----
{
  "common":  "{{string}}",
  "poly1": "{{string}}"
}
----

[source,json]
----
{
  "common":  "{{string}}",
  "poly2": "{{string}}"
}

----

You can check whether your json matches one or the other of those matchers by passing a list to `validator` this way:

[source,kotlin]
----
json(
    """{
          "common":  "a string",
          "poly2": "another string"
        }
    """
) matches validator(
    listOf(
        """{
              "common":  "{{string}}",
              "poly1": "{{string}}"
            }
        """,
        """{
              "common":  "{{string}}",
              "poly2": "{{string}}"
            }
        """
    )
)
----

== Lists

It works all the same for lists!

== Tips

For reading data easily from a JsonMap you may use function `JsonMap.getForPath(...)`
For exemple for a JsonMap representing that Json:
[source,json]
----
{
    "star": "wars",
    "characters": [
        { "luke": "skywalker" },
        { "han": "solo" },
        { "R2": "D2" }
    ]
}
----
You may use it like that:
[source,kotlin]
----
val jsonMap: JsonMap
val name1 = jsonMap.getForPath<String>("characters[0]", "luke") // == "skywalker"
val name2 = jsonMap.getForPath<String>("characters[1]", "han") // == "solo"
val name3 = jsonMap.getForPath<String>("characters[2]", "R2") // == "D2"
----

:leveloffset!:
:leveloffset: +1

= Gherkin support

Scenarios can be described in Gherkin and implemented with Kest.

== Big picture

Let's start with an example. +
Let's say we need to implement that scenario:

[source, gherkin]
----
Feature: Mathematics

    Scenario: Do some maths
        Given number 82
        When it is divided by 4
        And multiplied by sum of 1 and 2
        Then the result is 61.5
----

Then you would write it like that with Kest:
[source, kotlin]
----
@Given("number (.*)")
fun ScenarioBuilder.number(number: Int) = step { number }

@When("it is divided by (.*)")
fun ScenarioBuilder.divide(previousStep: StepResult<Int>, number: Long) = step { previousStep() / number }

@And("multiplied by sum of (.*) and (.*)")
fun ScenarioBuilder.multiplyBySumOf(previousStep: StepResult<Long>, s1: Double, s2: Float) =
    step { previousStep() * (s1 + s2) }

@Then("the result is (.*)")
fun ScenarioBuilder.operationResult(previousStep: StepResult<Double>, expectedResult: Double) =
    step { previousStep() } assertThat {
        it isEqualTo expectedResult
    }
----

* Annotations are set on functions which should be defined with these parameters:
    . previous step result (if needed)
    . parameters extracted from annotation regex (if any)

== Annotations

Five annotations are available to build steps from gherkin definitions. +
They are the link between your gherkin definition and your Kest steps implementations.

* `Given`
* `When`
* `Then`
* `But`
* `And`

There is no difference between these annotations, one could be used in place of another one.
They are declared on functions and take one parameter: a sentence that will match a Gherkin step definition. +
The sentence may contain regex to make steps customizable.

WARNING: if two annotations match a gherkin definition, then the first found by Kest will be used, take care when you define them, especially when they contain regex.

== Defining steps

To define a step you will create a function and annotate it with previously introduced annotations.

=== Parameters of function

==== Regex in annotation
When you set regex to your annotation' sentence, then you will have to pass the captured values of regex to your step function. +
Parameters should appear in the same order they are defined in annotation. +
Let's take that example:
[source, gherkin]
----
Feature: Mathematics

    Scenario: Do some maths
        Given numbers 3 and 4
        When they are added
        Then the result is 7
----
And let's implement step `Given numbers 3 and 4` +
We have several options:

. no customization +
+
----
@Given("numbers 3 and 4")
fun givenNumbers3And4() = step { 3 to 4 }
----
. customization +
+
----
@Given("numbers (.*) and (.*)")
fun givenNumbers(
    first: Int /* will receive value 3 */,
    second: Int /* will receive value 4 */,
) = step { first to second }
----

NOTE: Kest can automatically cast parameters extracted from regex of type String, Long, Int, Float, Double and Boolean, if you need another type you should declare it as String and build the correct type in your function.

==== Use a docstring defined on gherkin step

When writing gherkin steps you may use docstring to describe a complex data. +
For example:
[source, gherkin]
----
Feature: Films

    Scenario: Guess the theme
        Given a movie which starts with
        """
        A long time ago in a galaxy far, far away…

        It is a period of civil war.
        Rebel spaceships, striking
        from a hidden base, have won
        their first victory against
        the evil Galactic Empire.

        During the battle, Rebel
        spies managed to steal secret
        plans to the Empire's
        ultimate weapon, the DEATH
        STAR, an armored space
        station with enough power to
        destroy an entire planet.

        Pursued by the Empire's
        sinister agents, Princess
        Leia races home aboard her
        starship, custodian of the
        stolen plans that can save
        her people and restore
        freedom to the galaxy....
        """
        When it is displayed
        Then I hear "Main Title" from Star Wars: A New Hope
----
In that case you would implement it this way:
[source, kotlin]
----
@Given("a movie which starts with")
fun aMovieWhichStartsWith(text: String) = step { text }
----

More precisely, the docstring parameter must be the *LAST* parameter of your function.

==== Use the result of a previous step

If you need to reuse the result of a previous step you will have to declare it as first parameter of your function. +
Let's take that example:
[source, gherkin]
----
Feature: Mathematics

    Scenario: Do some maths
        Given numbers 3 and 4
        When they are added
        Then the result is 7
----
And let's implement step `When they are added` +
We will define it like this:
[source, kotlin]
----
@When("they are added")
fun theyAreAdded(previsousStep: StepResult<Pair<Int, Int>>) = step { previsousStep().first + previousStep().second }
----
let's implement step `Then the result is 7` +
[source, kotlin]
----
@Then("the result is (.*)")
fun theResultIs(previsousStep: StepResult<Int>, expectedResult: Int) = step { previsousStep() } assertThat { it isEqualTo expectedResult }
----

== Keep a context during scenario

You may one to keep a context while playing a gherkin scenario. +
It could be useful if you want to perform cleanups at the end oy your scenario: you could store everything you built in context and then end scenario with a cleanup step that would be responsible of cleaning all things stored in context.

For that:

. define a Context class that will extend `GherkinContext`
. at the end of a step call function `setGherkinScenarioContext<You_Context_Class>`
+
[source, kotlin]
----
data class MyContext(val stuff: List<String>): GherkinContext
scenario {

    step {
        "A long time ago in a galaxy far, far away…"
    } setGherkinScenarioContext  { context: MyContext?, stepRes ->

        context?.copy(stuff = context.stuff + listOf(stepRes)) ?: MyContext(listOf(stepRes))

    }
}
----
+
`setGherkinScenarioContext` takes as parameter a lambda that will be invoked with: +

.. current Gherkin Context (may be null if invoked for the first time)
.. the result of the step where you are invoking it.

The lambda should return the new value for your Gherkin Context.


== Play Gherkin scenarios

=== Default way

To allow Kest to detect your gherkin scenario you need to declare a class with `KestGherkin`annotation, it takes two parameters:

. `path`: classpath location where gherkin definitions are stored
. `stepDefinitionsPackage`: package where gherkin definition steps are implemented

By default `path`takes value `/gherkin` so no need to set it if you store your definitions in `src/test/resources/gherkin`

=== Custom way

If your Gherkin definitions are stored outside from your classpath you may use annotation `KestGherkinCustom` which will take an additional parameter `sourceProvider: +
`sourceProvider` is a KClass of an implementation of `KestGherkinFeaturesProvider`, in that implementation it is up to you to retrieve your Gherkin Features from wherever you need return them as a list of Strings

:leveloffset!:
:leveloffset: +1

= Configuration

You might want to access data from a configuration file. +
Kest configuration relies on https://github.com/sksamuel/hoplite +
You may add your entries in a file named kest.yaml which will be located at the root of your classpath +
All data from this file has to be mapped to a kotlin data class.

Then you can access your configuration by calling function `property`:

[source,yml,title=kest.yml]
----
mykey: myvalue
myotherkey: myothervalue

domain:
  akey: a value
  anotherkey: anothervalue
----

[source,kotlin,title="Configuration data class"]
----

data class Properties(
    val mykey: String,
    val myotherkey: String,
    val domain: Domain
)

data class Domain(
    val akey: String,
    val anotherkey: String
)
----

[source,kotlin,title="Access configuration"]
----
property(Properties::class) { myKey }
property(Properties::class) { myValue }
property(Properties::class) { domain.akey }
property(Properties::class) { domain.anotherkey }

// or with you may create your own shortcut:
fun <R> props(prop: Properties.() -> R) = property(Properties::class) { prop() }
// and then use it like that:
props { myKey }
props { myValue }
props { domain.akey }
props { domain.anotherkey }
----

== Change kest.yml location
If you need to set another location for Kest you can run tests with property `kest-conf` or environment variable `KEST_CONF` with the location you need

:leveloffset!:
