:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/lemfi/kest/main/
:title-logo-image: image:doc/logo.svg[]

= Kest image:doc/tinylogo.svg[alt=Kest, 55]

Kest is a framework written in Kotlin for testing your backends. +
It uses JUnit5 to run scenarios.

Easy to use, easy to extend.

== Use it

=== Gradle

[source,kotlin]
----
    implementation("com.github.lemfi.kest:core:0.6.9")
    implementation("com.github.lemfi.kest:junit5:0.6.9")

    // include the steps you need among available ones
    implementation("com.github.lemfi.kest:step-http:0.6.9")
    implementation("com.github.lemfi.kest:step-cadence:0.6.9")
    implementation("com.github.lemfi.kest:step-mongodb:0.6.9")
    implementation("com.github.lemfi.kest:step-rabbitmq:0.6.9")
    implementation("com.github.lemfi.kest:step-redis:0.6.9")

    // toolbox for Json Data
    implementation("com.github.lemfi.kest:json:0.6.9")

----

=== Maven

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>core</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>junit5</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>

    <!-- include the steps you need among available ones -->
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-http</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-rabbitmq</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-cadence</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-mongodb</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-redis</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>

    <!-- toolbox for Json Data -->
    <dependency>
        <groupId>com.github.lemfi.kest</groupId>
        <artifactId>step-json</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----

== Scenarios

Kest allows you to write scenarios. +
One scenario is a sequence of steps. +
One step defines an execution and a list of assertions to validate completed execution.

Let's take following example:

[source,kotlin]
----
scenario(name = "api says hello and remembers it!") {

    `given http call`<String> {

        url = "http://myapi/hello"
        method = "POST"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="
        body = """
            {
                "who": "Darth Vader"
            }
        """
    } `assert that` { stepResult ->

        eq(201, stepResult.status)
        eq("Hello Darth Vader!", stepResult.body)
    }

    `given http call`<String> {

        url = "http://myapi/hello"
        method = "POST"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="
        body = """
            {
                "who": "Han Solo"
            }
        """
    } `assert that` { stepResult ->

        eq(201, stepResult.status)
        eq("Hello Han Solo!", stepResult.body)
    }

    `given http call`<List<String>> {

        url = "http://myapi/hello"
        method = "GET"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="

    } `assert that` { stepResult ->

        eq(200, stepResult.status)
        eq(listOf("Darth Vader", "Han Solo"), stepResult.body)
    }
}
----

This example defines a scenario with three steps:

. Say hello to Darth Vader
. Say hello to Han Solo
. Get list of people that were greeted

For each step 2 assertions are done:

. check status code
. check body

== Run a scenario

To run a scenario Kest uses Junit5 engine:

. Create a class to hold your test
. Create a function annotated with Junit5 `@TestFactory`
. Make it call Kest function
.. `play scenarios` to play multiple scenarios in a single junit5 test factory +
=> in this case you can pass `beforeEach` and `afterEach` attributes representing a lambda returning a scenario to be played before and after each scenario if needed.
.. `play scenario` to play one scenario per junit5 test factory +
=> in this case you can use junit5 annotations `@BeforeEach` and `@AfterEach`

[source,kotlin]
----

class TestHttpServer {

    @TestFactory
    fun `http server says hello`() = `play scenarios`(
            scenario { /*...*/ },
            scenario { /*...*/ },
            scenario { /*...*/ },

            beforeEach = { scenario { /*...*/ }},
            afterEach = { scenario { /*...*/ }}
    )


    @TestFactory
    fun `http server says goodbye`() = `play scenarios`(
            scenario { /*...*/ },
            scenario { /*...*/ },
            scenario { /*...*/ },

            beforeEach = { scenario { /*...*/ }},
            afterEach = { scenario { /*...*/ }}
    )

}

class TestHttpServer {

    @BeforeEach
    fun beforeEach() {
        /*...*/
    }

    @AfterEach
    fun afterEach() {
        /*...*/
    }

    @TestFactory
    fun `http server says hello - scenario 1`() = `play scenario`(
            scenario { /*...*/ }
    )

    @TestFactory
    fun `http server says hello - scenario 2`() = `play scenario`(
            scenario { /*...*/ }
    )

}
----

== It's Kotlin make it easy to read!

A scenario may become a long list of steps, not easily readable. +
Why do not extract steps to external functions, it will also make them reusable: double gain!

[source,kotlin]
----

@Suppress("unused")
fun ScenarioBuilder.`say hello`(who: String) {
    `given http call`<String> {

        url = "http://localhost:8080/hello"
        method = "POST"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="
        body = """
            {
                "who": "$who"
            }
            """
    } `assert that` { stepResult ->

        eq(201, stepResult.status)
        eq("Hello $who!", stepResult.body)
    }
}

@Suppress("unused")
fun ScenarioBuilder.`get greeted`(vararg expectedGreeted: String) {
    `given http call`<List<String>> {

        url = "http://localhost:8080/hello"
        method = "GET"
        headers["Authorization"] = "Basic aGVsbG86d29ybGQ="

    } `assert that` { stepResult ->

        eq(200, stepResult.status)
        eq(expectedGreeted.toList(), stepResult.body)
    }
}


class TestHttpServer {

    @TestFactory
    fun `http server hello`() = `play scenarios`(
            scenario(name = "api says hello and remembers it!") {

                `say hello`("Darth Vader")
                `say hello`("Han Solo")

                `get greeted`("Darth Vader", "Han Solo")
            },
            beforeEach = ::startSampleApi,
            afterEach = ::stopSampleApi
    )

    @TestFactory
    fun `http server goodbye`() = `play scenarios`(
            scenario(name = "api says goodbye and forgets people!") {

                `say hello`("Darth Vader")
                `say hello`("Han Solo")

                `given http call`<String> {

                    url = "http://localhost:8080/hello?who=Darth Vader"
                    method = "DELETE"
                    headers["Authorization"] = "Basic aGVsbG86d29ybGQ="

                } `assert that` { stepResult ->

                    eq(201, stepResult.status)
                    eq("Goodbye Darth Vader!", stepResult.body)
                }

                `get greeted`("Han Solo")

            },
            beforeEach = ::startSampleApi,
            afterEach = ::stopSampleApi
    )
}

----

And again, we can also extract scenarios

[source,kotlin]
----

val `api says hello and remembers it!` = scenario(name = "api says hello and remembers it!") {

    `say hello`("Darth Vader")
    `say hello`("Han Solo")

    `get greeted`("Darth Vader", "Han Solo")
}

val `api says goodbye and forgets people!` = scenario(name = "api says goodbye and forgets people!") {

            `say hello`("Darth Vader")
            `say hello`("Han Solo")

            `given http call`<String> {

                url = "http://localhost:8080/hello?who=Darth Vader"
                method = "DELETE"
                headers["Authorization"] = "Basic aGVsbG86d29ybGQ="

            } `assert that` { stepResult ->

                eq(201, stepResult.status)
                eq("Goodbye Darth Vader!", stepResult.body)
            }

            `get greeted`("Han Solo")

        }


class TestHttpServer {

    @TestFactory
    fun `http server hello`() = `play scenarios`(
            `api says hello and remembers it!`,

            beforeEach = ::startSampleApi,
            afterEach = ::stopSampleApi
    )

    @TestFactory
    fun `http server goodbye`() = `play scenarios`(
           `api says goodbye and forgets people!`,

            beforeEach = ::startSampleApi,
            afterEach = ::stopSampleApi
    )

    @TestFactory
    fun `http server hello and goodbye`() = `play scenarios`(
            `api says hello and remembers it!`,
            `api says goodbye and forgets people!`,

            beforeEach = ::startSampleApi,
            afterEach = ::stopSampleApi
    )
}

----

== Focus on how it works

image::{gitplant}/doc/diag/model.puml[]

When a scenario is launched, all its steps are launched sequentially, if one step fails the scenario fails without running remaining steps. +
When a step is launched its execution is played, then assertions are played against execution result. +
A step returns an object . which is invokable: you may reuse its result in another step . which you may complete by your own assertions, they will be added to assertions already defined on step

== Available Steps

* link:step-http/README.adoc[HTTP]
* link:step-rabbitmq/README.adoc[RabbitMQ]
* Mongo
* Redis
* Cadence

== Json Toolbox

A bunch of tools are available to work on Json data, `step-http` module exposes it by default.
If not using `step-http` but still need those tools, add module json to your dependencies.

link:json/README.adoc[Json Toolbox]

== Configuration

You might want to access data from a configuration file.
Kest offers you to add your entries in a file named kest.yaml All data from this file has to be mapped to a kotlin data class.

Then you can access your configuration by calling function `property`:

[source,yml,title=kest.yml]
----
mykey: myvalue
myotherkey: myothervalue

domain:
  akey: a value
  anotherkey: anothervalue
----

[source,kotlin,title="Configuration data class"]
----

data class Properties(
    val mykey: String,
    val myotherkey: String,
    val domain: Domain
)

data class Domain(
    val akey: String,
    val anotherkey: String
)
----

[source,kotlin,title="Access configuration"]
----
property(Properties::class) { myKey }
property(Properties::class) { myValue }
property(Properties::class) { domain.akey }
property(Properties::class) { domain.anotherkey }
----
