:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/lemfi/kest/main/

= JSON support

JSON is a common format to interact between machines, as matter of fact, Kest comes with advanced support to that format with a bunch of assertions. +
It also comes with two Objects: `JsonMap` and `JsonArray`

* `JsonMap` is a `Map<String, Any?>`
* `JsonArray` is an array of `JsonMap`

== Matchers

Kest provides several function to check whether a json content matches a Json pattern.
To do so, Kest provides by default 3 matchers:

- {{string}}
- {{number}}
- {{boolean}}

For example

[source,json]
----
{
  "string": "a string",
  "number": 1,
  "boolean": true
}
----

is matched by

[source,json]
----
{
  "string": "{{string}}",
  "number": "{{number}}",
  "boolean": "{{boolean}}"
}
----

or by

[source,json]
----
{
  "string": "{{string}}",
  "number": 1,
  "boolean": "{{boolean}}"
}
----

And the function to check that with Kest would be:

[source,kotlin]
----
jsonMatches(
"""
{
  "string": "{{string}}",
  "number": "{{number}}",
  "boolean": "{{boolean}}"
}
""",
"""
{
  "string": "a string",
  "number": 1,
  "boolean": true
}""")
----

=== Defining your own matchers

If you want to define your own matchers, two possibilities:

==== Define a class

[source,kotlin]
----
data class Sample(
        val string: String,
        val number: Int,
        val boolean: Boolean
)
----

Then call JsonMatcher.addMatcher function with the class and the pattern that will represent it:

[source,kotlin]
----
`add json matcher`("{{sample}}", Sample::class)
----

To check match you can now call this:

[source,kotlin]
----
jsonMatches(
"""
{{sample}}}
""",
"""
{
  "string": "a string",
  "number": 1,
  "boolean": true
}""")
----

== Polymorphism

To go through polyphormism, Kest allows you to define a list of matchers for a given JSON.

Let's take this example:

[source,json]
----
{
  "common":  "{{string}}",
  "poly1": "{{string}}"
}
----

[source,json]
----
{
  "common":  "{{string}}",
  "poly2": "{{string}}"
}

----

You can check whether your json matches one or the other of those matchers by passing a list to `jsonMatches` function:

[source,kotlin]
----
jsonMatches(
                listOf(
                """{
                      "common":  "{{string}}",
                      "poly1": "{{string}}"
                    }
                """,
                """{
                      "common":  "{{string}}",
                      "poly2": "{{string}}"
                    }
                """
                ),
                 """{
                      "common":  "a string",
                      "poly2": "another string"
                    }
                """
        )
----

== Lists

It works all the same for lists!

== Tips

For reading data easily from a JsonMap you may use function `JsonMap.getForPath(...)`
For exemple for a JsonMap representing that Json:
[source,json]
----
{
    "star": "wars",
    "characters": [
        { "luke": "skywalker" },
        { "han": "solo" },
        { "R2": "D2" }
    ]
}
----
You may use it like that:
[source,kotlin]
----
val jsonMap: JsonMap
val name1 = jsonMap.getForPath<String>("characters[0]", "luke") // == "skywalker"
val name2 = jsonMap.getForPath<String>("characters[1]", "han") // == "solo"
val name3 = jsonMap.getForPath<String>("characters[2]", "R2") // == "D2"
----